### ISSUE TITLE
System.OutOfMemoryException in MySQL inserting one million rows

### ISSUE THREAD

**Issue by Anshem** [zzzprojects/Bulk-Operations#5]
Hello, 
I'm trying to insert 1 million rows in a table with 3 columns and I have an out of memory exception, this is the stack trace:

```
at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.AppendHelper(String value)
   at System.Text.StringBuilder.Append(String value)
   at ..(BulkOperation , DbCommand )
   at ..(DbCommand , BulkOperation )
   at ..( , DbCommand )
   at ..(List`1 )
   at ..(List`1 )
   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.BulkOperations.BulkOperation.BulkInsert(Object datasource)
```

Could you please help me?

Thanks in advance.

**Comment by zzzprojects** [comment]
Hello @Anshem ,

I'm pretty sure you still have the log enabled. Unfortunately for MySQL, it logs a LOT of stuff... So for one millions records, I'm pretty sure that will hit the limit of what a StringBuilder can hold.

So just disabling it should get rid of this error.

Let me know if that worked or you absolutely need the log enabled.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Anshem ,

Did you success to make it work?

Can we close this issue?

Best Regards,

Jonathan

**Comment by Anshem** [comment]
Sorry for the delay, yes, the problem was solved.

**Comment by JonathanMagnan** [comment]
Closing Comment: Issue fixed confirmed
